# Root Directory
artifacts_root: artifacts

# Data Ingestion
data_ingestion:
  root_dir: artifacts/data_ingestion
  sourceURL: https://github.com/Roshilv3/all_Datasets/raw/main/data_spotify.zip
  local_file_dir: artifacts/data_ingestion/data_spotify.zip
  unzip_dir: artifacts/data_ingestion

# Data Transformation
data_validation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/data_spotify.csv
  STATUS_FILE_DIR: artifacts/data_validation/status.txt

# Data Cleaning
data_cleaning:
  root_dir: artifacts/data_cleaning
  data_dir: artifacts/data_ingestion/data_spotify.csv
  new_data_dir: artifacts/data_cleaning

# Data Transformation
data_transformation:
  root_dir: artifacts/data_transformation
  data_dir: artifacts/data_cleaning/data_spotify_new.csv

# Model Trainer
model_trainer:
  root_dir: artifacts/model_trainer
  train_tfidf: artifacts/data_transformation/train_tfidf.csv.npz
  test_tfidf: artifacts/data_transformation/test_tfidf.csv.npz
  train_y: artifacts/data_transformation/train.csv
  test_y: artifacts/data_transformation/test.csv
  model_name: model.joblib

# Model Evaluation
model_evaluation:
  root_dir: artifacts/model_evaluation
  test_tfidf: artifacts/data_transformation/test_tfidf.csv.npz
  test_y: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metrics_file_path: artifacts/model_evaluation/metric.json